### ISSUE TITLE
Compatibility request for Liferay Portal 7.3.4-ce-ga5 CE

### ISSUE THREAD

**Issue by icarrara** [amusarra/scheduler-manager-gogoshell-command#1]
Tried to install on Liferay Portal 7.3.4 GA5 CE.

Got the below error:

`2020-09-27 13:52:06.120 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:271] Processing it.dontesta.labs.liferay.gogo.scheduler.manager-1.3.0.jar
2020-09-27 13:52:11.877 ERROR [fileinstall-C:/dev/liferay/7.3.4-ce-ga5/portal/osgi/modules][DirectoryWatcher:1112] Unable to start bundle: file:/C:/dev/liferay/7.3.4-ce-ga5/portal/osgi/modules/it.dontesta.labs.liferay.gogo.scheduler.manager-1.3.0.jar
org.osgi.framework.BundleException: Could not resolve module: it.dontesta.labs.liferay.gogo.scheduler.manager [1202]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.exception; version="[8.0.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1095)
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1128)
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:990)
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:302)
`

Deploy fails.

I'm available to test the adaptation for 7.3.4 GA5 CE.

**Comment by amusarra** [comment]
Hi @icarrara 
I just release the 1.4.0 version that support Liferay 7.3 GA5.  You can test this directly downloading the package (jar) from Package section and install it on your Liferay instance.

Let me know if it works, so I close the issue afterwards.

**Comment by icarrara** [comment]
Tested with Liferay Portal Liferay 7.3 GA5.

Deploy: 
`[com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:271] Processing it.dontesta.labs.liferay.gogo.scheduler.manager-1.4.0.jar
[fileinstall-C:/dev/liferay/7.3.4-ce-ga5/portal/osgi/modules][BundleStartStopLogger:46] STARTED it.dontesta.labs.liferay.gogo.scheduler.manager_1.4.0 [1200]
`

From Portal's Gogo Shell issued the below command:
`scheduler:info com.liferay.asset.publisher.web.internal.messaging.CheckAssetEntryMessageListener com.liferay.asset.publisher.web.internal.messaging.CheckAssetEntryMessageListener MEMORY_CLUSTERED`

Portal's result: ok - see screen shot.
![7 3 4-GA5-tested-ok](https://user-images.githubusercontent.com/2285400/94408643-5b548800-0175-11eb-84ef-f74053af1d81.JPG)
